# Generated by Django 5.0.6 on 2024-06-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_name', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('harvest_time', models.CharField(max_length=50)),
            ],
        ),
    ]
