# Generated by Django 5.0.6 on 2024-06-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record_price_record_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='price',
            field=models.CharField(default=30, max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='quantity',
            field=models.CharField(default=5, max_length=50),
        ),
    ]
